const INTERNAL_EVENTS = [
  'meta',
  'onStarted',
  'onReady',
  'onDisplayError',
  'onResized',
  'onLocationChange',
  'onSearch',
  'onLocationsReady',
  'onSelected',
  'onUnselected',
  'onOrientationChange',
  'onBeginning',
  'onFinish',
  'onRendered',
  'onLayout',
  'onNavigationLoaded',
  'onAddAnnotation',
  'onChangeAnnotations',
  'onSetInitialAnnotations',
  'onPressAnnotation',
  'onPressFootnote',
  'onScroll',
  'onAddBookmark',
  'onRemoveBookmark',
  'onRemoveBookmarks',
  'onUpdateBookmark',
];

export default INTERNAL_EVENTS;
